source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/1326B/1326B_sm.hdf -pp -i 1326B -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP1734/HIP1734_sm.hdf -pp -i HIP1734 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP5643/HIP5643_sm.hdf -pp -i HIP5643 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP8051/HIP8051_sm.hdf -pp -i HIP8051 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/GL83.1/GL83.1_sm.hdf -pp -i GL83.1 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/GL87/GL87_sm.hdf -pp -i GL87 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP11048/HIP11048_sm.hdf -pp -i HIP11048 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/GL105B/GL105B_sm.hdf -pp -i GL105B -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/GL109/GL109_sm.hdf -pp -i GL109 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP15366/HIP15366_sm.hdf -pp -i HIP15366 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/28343/28343_sm.hdf -pp -i 28343 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/232979/232979_sm.hdf -pp -i 232979 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP21556/HIP21556_sm.hdf -pp -i HIP21556 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP22762/HIP22762_sm.hdf -pp -i HIP22762 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP23512/HIP23512_sm.hdf -pp -i HIP23512 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/245409/245409_sm.hdf -pp -i 245409 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/GL239/GL239_sm.hdf -pp -i GL239 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/GL250B/GL250B_sm.hdf -pp -i GL250B -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/265866/265866_sm.hdf -pp -i 265866 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/GL273/GL273_sm.hdf -pp -i GL273 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP36338/HIP36338_sm.hdf -pp -i HIP36338 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP36834/HIP36834_sm.hdf -pp -i HIP36834 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP37217/HIP37217_sm.hdf -pp -i HIP37217 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/GL2066/GL2066_sm.hdf -pp -i GL2066 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP46769/HIP46769_sm.hdf -pp -i HIP46769 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP47513/HIP47513_sm.hdf -pp -i HIP47513 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/GL382/GL382_sm.hdf -pp -i GL382 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP51007/HIP51007_sm.hdf -pp -i HIP51007 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/GL393/GL393_sm.hdf -pp -i GL393 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP57050/HIP57050_sm.hdf -pp -i HIP57050 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP57548/HIP57548_sm.hdf -pp -i HIP57548 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP59748/HIP59748_sm.hdf -pp -i HIP59748 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP60093/HIP60093_sm.hdf -pp -i HIP60093 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP61706/HIP61706_sm.hdf -pp -i HIP61706 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/111631/111631_sm.hdf -pp -i 111631 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP65016/HIP65016_sm.hdf -pp -i HIP65016 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/GL514/GL514_sm.hdf -pp -i GL514 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP71253/HIP71253_sm.hdf -pp -i HIP71253 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/GL625/GL625_sm.hdf -pp -i GL625 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/GJ628/GJ628_sm.hdf -pp -i GJ628 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/157881/157881_sm.hdf -pp -i 157881 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/GL686/GL686_sm.hdf -pp -i GL686 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/GL694/GL694_sm.hdf -pp -i GL694 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/165222/165222_sm.hdf -pp -i 165222 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP91699/HIP91699_sm.hdf -pp -i HIP91699 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/GL745A/GL745A_sm.hdf -pp -i GL745A -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/180617/180617_sm.hdf -pp -i 180617 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/GL806/GL806_sm.hdf -pp -i GL806 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP104432/HIP104432_sm.hdf -pp -i HIP104432 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/209290/209290_sm.hdf -pp -i 209290 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP109388/HIP109388_sm.hdf -pp -i HIP109388 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/GL875/GL875_sm.hdf -pp -i GL875 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP115332/HIP115332_sm.hdf -pp -i HIP115332 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP115562/HIP115562_sm.hdf -pp -i HIP115562 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/GL896A/GL896A_sm.hdf -pp -i GL896A -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/GL908/GL908_sm.hdf -pp -i GL908 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/16895/16895_sm.hdf -pp -i 16895 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/22484/22484_sm.hdf -pp -i 22484 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/34411/34411_sm.hdf -pp -i 34411 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/39587/39587_sm.hdf -pp -i 39587 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/48737/48737_sm.hdf -pp -i 48737 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/58946/58946_sm.hdf -pp -i 58946 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/82885/82885_sm.hdf -pp -i 82885 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/86728/86728_sm.hdf -pp -i 86728 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/101501/101501_sm.hdf -pp -i 101501 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/131156/131156_sm.hdf -pp -i 131156 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/164259/164259_sm.hdf -pp -i 164259 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/173667/173667_sm.hdf -pp -i 173667 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/182572/182572_sm.hdf -pp -i 182572 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/222368/222368_sm.hdf -pp -i 222368 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/166/166_sm.hdf -pp -i 166 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/6210/6210_sm.hdf -pp -i 6210 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/16765/16765_sm.hdf -pp -i 16765 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/38858/38858_sm.hdf -pp -i 38858 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/69897/69897_sm.hdf -pp -i 69897 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/130948/130948_sm.hdf -pp -i 130948 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/158633/158633_sm.hdf -pp -i 158633 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/168151/168151_sm.hdf -pp -i 168151 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/186408/186408_sm.hdf -pp -i 186408 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/186427/186427_sm.hdf -pp -i 186427 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/206860/206860_sm.hdf -pp -i 206860 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/219623/219623_sm.hdf -pp -i 219623 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/75732/75732_sm.hdf -pp -i 75732 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/190406/190406_sm.hdf -pp -i 190406 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/49933/49933_sm.hdf -pp -i 49933 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/3651/3651_sm.hdf -pp -i 3651 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/19994/19994_sm.hdf -pp -i 19994 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/117176/117176_sm.hdf -pp -i 117176 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/120136/120136_sm.hdf -pp -i 120136 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/190360/190360_sm.hdf -pp -i 190360 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/161797/161797_sm.hdf -pp -i 161797 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/188512/188512_sm.hdf -pp -i 188512 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/10700/10700_sm.hdf -pp -i 10700 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/23249/23249_sm.hdf -pp -i 23249 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/21019/21019_sm.hdf -pp -i 21019 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/136202/136202_sm.hdf -pp -i 136202 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/157214/157214_sm.hdf -pp -i 157214 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/195564/195564_sm.hdf -pp -i 195564 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/19373/19373_sm.hdf -pp -i 19373 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/30652/30652_sm.hdf -pp -i 30652 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/126660/126660_sm.hdf -pp -i 126660 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/173701/173701_sm.hdf -pp -i 173701 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/177153/177153_sm.hdf -pp -i 177153 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/181420/181420_sm.hdf -pp -i 181420 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/182736/182736_sm.hdf -pp -i 182736 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/187637/187637_sm.hdf -pp -i 187637 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/217014/217014_sm.hdf -pp -i 217014 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/10476/10476_sm.hdf -pp -i 10476 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/10697/10697_sm.hdf -pp -i 10697 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/11964A/11964A_sm.hdf -pp -i 11964A -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/217107/217107_sm.hdf -pp -i 217107 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/4628/4628_sm.hdf -pp -i 4628 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/16160/16160_sm.hdf -pp -i 16160 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/36395/36395_sm.hdf -pp -i 36395 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/79210/79210_sm.hdf -pp -i 79210 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/GL338B/GL338B_sm.hdf -pp -i GL338B -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/GL412A/GL412A_sm.hdf -pp -i GL412A -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/119850/119850_sm.hdf -pp -i 119850 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/149661/149661_sm.hdf -pp -i 149661 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/GL687/GL687_sm.hdf -pp -i GL687 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/GL702A/GL702A_sm.hdf -pp -i GL702A -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/GL702B/GL702B_sm.hdf -pp -i GL702B -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/173739/173739_sm.hdf -pp -i 173739 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/173740/173740_sm.hdf -pp -i 173740 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/199305/199305_sm.hdf -pp -i 199305 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/216899/216899_sm.hdf -pp -i 216899 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/219134/219134_sm.hdf -pp -i 219134 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/10780/10780_sm.hdf -pp -i 10780 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/GL144/GL144_sm.hdf -pp -i GL144 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP57087/HIP57087_sm.hdf -pp -i HIP57087 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/GL570B/GL570B_sm.hdf -pp -i GL570B -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP74995/HIP74995_sm.hdf -pp -i HIP74995 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/185144/185144_sm.hdf -pp -i 185144 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/1326/1326_sm.hdf -pp -i 1326 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/26965/26965_sm.hdf -pp -i 26965 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/88230/88230_sm.hdf -pp -i 88230 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/95735/95735_sm.hdf -pp -i 95735 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/GL699/GL699_sm.hdf -pp -i GL699 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/201091/201091_sm.hdf -pp -i 201091 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/201092/201092_sm.hdf -pp -i 201092 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/217987/217987_sm.hdf -pp -i 217987 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/115617/115617_sm.hdf -pp -i 115617 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/143761/143761_sm.hdf -pp -i 143761 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/GJ176/GJ176_sm.hdf -pp -i GJ176 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/145675/145675_sm.hdf -pp -i 145675 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP83043/HIP83043_sm.hdf -pp -i HIP83043 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/GL876/GL876_sm.hdf -pp -i GL876 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/1461/1461_sm.hdf -pp -i 1461 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/7924/7924_sm.hdf -pp -i 7924 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/107383/107383_sm.hdf -pp -i 107383 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/210702/210702_sm.hdf -pp -i 210702 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC1435467/KIC1435467_sm.hdf -pp -i KIC1435467 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC3427720/KIC3427720_sm.hdf -pp -i KIC3427720 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/K00975/K00975_sm.hdf -pp -i K00975 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC3656476/KIC3656476_sm.hdf -pp -i KIC3656476 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC4914923/KIC4914923_sm.hdf -pp -i KIC4914923 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC5021689/KIC5021689_sm.hdf -pp -i KIC5021689 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC5184732/KIC5184732_sm.hdf -pp -i KIC5184732 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC5596656/KIC5596656_sm.hdf -pp -i KIC5596656 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC5773345/KIC5773345_sm.hdf -pp -i KIC5773345 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC5955122/KIC5955122_sm.hdf -pp -i KIC5955122 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC6106415/KIC6106415_sm.hdf -pp -i KIC6106415 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC6116048/KIC6116048_sm.hdf -pp -i KIC6116048 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC6225718/KIC6225718_sm.hdf -pp -i KIC6225718 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC6442183/KIC6442183_sm.hdf -pp -i KIC6442183 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC6603624/KIC6603624_sm.hdf -pp -i KIC6603624 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC6933899/KIC6933899_sm.hdf -pp -i KIC6933899 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC7206837/KIC7206837_sm.hdf -pp -i KIC7206837 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC7680114/KIC7680114_sm.hdf -pp -i KIC7680114 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC7747078/KIC7747078_sm.hdf -pp -i KIC7747078 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC7799349/KIC7799349_sm.hdf -pp -i KIC7799349 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC7871531/KIC7871531_sm.hdf -pp -i KIC7871531 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC7940546/KIC7940546_sm.hdf -pp -i KIC7940546 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC7970740/KIC7970740_sm.hdf -pp -i KIC7970740 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC7976303/KIC7976303_sm.hdf -pp -i KIC7976303 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC8006161/KIC8006161_sm.hdf -pp -i KIC8006161 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC8179536/KIC8179536_sm.hdf -pp -i KIC8179536 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC8228742/KIC8228742_sm.hdf -pp -i KIC8228742 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC8394589/KIC8394589_sm.hdf -pp -i KIC8394589 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC8524425/KIC8524425_sm.hdf -pp -i KIC8524425 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC8561221/KIC8561221_sm.hdf -pp -i KIC8561221 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC8694723/KIC8694723_sm.hdf -pp -i KIC8694723 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC8702606/KIC8702606_sm.hdf -pp -i KIC8702606 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC8751420/KIC8751420_sm.hdf -pp -i KIC8751420 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC8938364/KIC8938364_sm.hdf -pp -i KIC8938364 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC9098294/KIC9098294_sm.hdf -pp -i KIC9098294 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC9139151/KIC9139151_sm.hdf -pp -i KIC9139151 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC9139163/KIC9139163_sm.hdf -pp -i KIC9139163 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC9206432/KIC9206432_sm.hdf -pp -i KIC9206432 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/CK01925/CK01925_sm.hdf -pp -i CK01925 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC10018963/KIC10018963_sm.hdf -pp -i KIC10018963 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC10068307/KIC10068307_sm.hdf -pp -i KIC10068307 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC10162436/KIC10162436_sm.hdf -pp -i KIC10162436 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC10355856/KIC10355856_sm.hdf -pp -i KIC10355856 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC10454113/KIC10454113_sm.hdf -pp -i KIC10454113 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC10516096/KIC10516096_sm.hdf -pp -i KIC10516096 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC10644253/KIC10644253_sm.hdf -pp -i KIC10644253 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC10709834/KIC10709834_sm.hdf -pp -i KIC10709834 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/K01612/K01612_sm.hdf -pp -i K01612 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC11026764/KIC11026764_sm.hdf -pp -i KIC11026764 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC11137075/KIC11137075_sm.hdf -pp -i KIC11137075 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC11244118/KIC11244118_sm.hdf -pp -i KIC11244118 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC11414712/KIC11414712_sm.hdf -pp -i KIC11414712 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC11717120/KIC11717120_sm.hdf -pp -i KIC11717120 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC12009504/KIC12009504_sm.hdf -pp -i KIC12009504 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC12258514/KIC12258514_sm.hdf -pp -i KIC12258514 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/120467/120467_sm.hdf -pp -i 120467 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP104092/HIP104092_sm.hdf -pp -i HIP104092 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/21197/21197_sm.hdf -pp -i 21197 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/190007/190007_sm.hdf -pp -i 190007 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/10853/10853_sm.hdf -pp -i 10853 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/127506/127506_sm.hdf -pp -i 127506 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/170493/170493_sm.hdf -pp -i 170493 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/65486/65486_sm.hdf -pp -i 65486 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/213042/213042_sm.hdf -pp -i 213042 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/11373/11373_sm.hdf -pp -i 11373 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/202575/202575_sm.hdf -pp -i 202575 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/39715/39715_sm.hdf -pp -i 39715 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/144872/144872_sm.hdf -pp -i 144872 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/130992/130992_sm.hdf -pp -i 130992 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/202751/202751_sm.hdf -pp -i 202751 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/263175/263175_sm.hdf -pp -i 263175 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/130871/130871_sm.hdf -pp -i 130871 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/215152/215152_sm.hdf -pp -i 215152 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/53927/53927_sm.hdf -pp -i 53927 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/25665/25665_sm.hdf -pp -i 25665 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/136834/136834_sm.hdf -pp -i 136834 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/5133/5133_sm.hdf -pp -i 5133 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/216259/216259_sm.hdf -pp -i 216259 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/4256/4256_sm.hdf -pp -i 4256 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/18632/18632_sm.hdf -pp -i 18632 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP94931/HIP94931_sm.hdf -pp -i HIP94931 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/3765/3765_sm.hdf -pp -i 3765 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/220339/220339_sm.hdf -pp -i 220339 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/130307/130307_sm.hdf -pp -i 130307 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/219538/219538_sm.hdf -pp -i 219538 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/59747/59747_sm.hdf -pp -i 59747 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/124106/124106_sm.hdf -pp -i 124106 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/17190/17190_sm.hdf -pp -i 17190 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/132142/132142_sm.hdf -pp -i 132142 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/144579/144579_sm.hdf -pp -i 144579 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/10002/10002_sm.hdf -pp -i 10002 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/225261/225261_sm.hdf -pp -i 225261 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/11020/11020_sm.hdf -pp -i 11020 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP1532/HIP1532_sm.hdf -pp -i HIP1532 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP10337/HIP10337_sm.hdf -pp -i HIP10337 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP47201/HIP47201_sm.hdf -pp -i HIP47201 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP66222/HIP66222_sm.hdf -pp -i HIP66222 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP4845/HIP4845_sm.hdf -pp -i HIP4845 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP40910/HIP40910_sm.hdf -pp -i HIP40910 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP12493/HIP12493_sm.hdf -pp -i HIP12493 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP19165/HIP19165_sm.hdf -pp -i HIP19165 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP93871/HIP93871_sm.hdf -pp -i HIP93871 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP15095/HIP15095_sm.hdf -pp -i HIP15095 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP105341/HIP105341_sm.hdf -pp -i HIP105341 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP114156/HIP114156_sm.hdf -pp -i HIP114156 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP118261/HIP118261_sm.hdf -pp -i HIP118261 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP25220/HIP25220_sm.hdf -pp -i HIP25220 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP97051/HIP97051_sm.hdf -pp -i HIP97051 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP36551/HIP36551_sm.hdf -pp -i HIP36551 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP40375/HIP40375_sm.hdf -pp -i HIP40375 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP5663/HIP5663_sm.hdf -pp -i HIP5663 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP45839/HIP45839_sm.hdf -pp -i HIP45839 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP48411/HIP48411_sm.hdf -pp -i HIP48411 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP54651/HIP54651_sm.hdf -pp -i HIP54651 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/HIP54810/HIP54810_sm.hdf -pp -i HIP54810 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/64413/64413_sm.hdf -pp -i 64413 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/26007/26007_sm.hdf -pp -i 26007 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/9625/9625_sm.hdf -pp -i 9625 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/123239/123239_sm.hdf -pp -i 123239 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/3458/3458_sm.hdf -pp -i 3458 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/130048/130048_sm.hdf -pp -i 130048 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/26634/26634_sm.hdf -pp -i 26634 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/8407/8407_sm.hdf -pp -i 8407 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/8594/8594_sm.hdf -pp -i 8594 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/108863/108863_sm.hdf -pp -i 108863 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/114659/114659_sm.hdf -pp -i 114659 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/18742/18742_sm.hdf -pp -i 18742 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/152733/152733_sm.hdf -pp -i 152733 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/22657/22657_sm.hdf -pp -i 22657 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/15336/15336_sm.hdf -pp -i 15336 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/238433/238433_sm.hdf -pp -i 238433 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/210373/210373_sm.hdf -pp -i 210373 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/1502/1502_sm.hdf -pp -i 1502 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/199381/199381_sm.hdf -pp -i 199381 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/77818/77818_sm.hdf -pp -i 77818 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/95526/95526_sm.hdf -pp -i 95526 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/72490/72490_sm.hdf -pp -i 72490 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/200964/200964_sm.hdf -pp -i 200964 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/74390/74390_sm.hdf -pp -i 74390 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/14787/14787_sm.hdf -pp -i 14787 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/4313/4313_sm.hdf -pp -i 4313 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/6030/6030_sm.hdf -pp -i 6030 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/61995/61995_sm.hdf -pp -i 61995 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/207077/207077_sm.hdf -pp -i 207077 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/152581/152581_sm.hdf -pp -i 152581 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/199255/199255_sm.hdf -pp -i 199255 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/190571/190571_sm.hdf -pp -i 190571 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/48345/48345_sm.hdf -pp -i 48345 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/31451/31451_sm.hdf -pp -i 31451 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/125607/125607_sm.hdf -pp -i 125607 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/122253/122253_sm.hdf -pp -i 122253 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/102956/102956_sm.hdf -pp -i 102956 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/216834/216834_sm.hdf -pp -i 216834 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/14855/14855_sm.hdf -pp -i 14855 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/135872/135872_sm.hdf -pp -i 135872 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/40537/40537_sm.hdf -pp -i 40537 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/217681/217681_sm.hdf -pp -i 217681 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/17620/17620_sm.hdf -pp -i 17620 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/109159/109159_sm.hdf -pp -i 109159 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/206635/206635_sm.hdf -pp -i 206635 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/57204/57204_sm.hdf -pp -i 57204 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/108189/108189_sm.hdf -pp -i 108189 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/88654/88654_sm.hdf -pp -i 88654 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/102444/102444_sm.hdf -pp -i 102444 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/4395/4395_sm.hdf -pp -i 4395 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/215049/215049_sm.hdf -pp -i 215049 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/95088/95088_sm.hdf -pp -i 95088 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/10995/10995_sm.hdf -pp -i 10995 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/203471/203471_sm.hdf -pp -i 203471 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/190228/190228_sm.hdf -pp -i 190228 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/93396/93396_sm.hdf -pp -i 93396 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/23825/23825_sm.hdf -pp -i 23825 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/72440/72440_sm.hdf -pp -i 72440 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/221504/221504_sm.hdf -pp -i 221504 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/155413/155413_sm.hdf -pp -i 155413 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/3404/3404_sm.hdf -pp -i 3404 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/106088/106088_sm.hdf -pp -i 106088 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/88133/88133_sm.hdf -pp -i 88133 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/3684/3684_sm.hdf -pp -i 3684 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/45067/45067_sm.hdf -pp -i 45067 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/14655/14655_sm.hdf -pp -i 14655 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/111814/111814_sm.hdf -pp -i 111814 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/39094/39094_sm.hdf -pp -i 39094 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/24892/24892_sm.hdf -pp -i 24892 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/148284/148284_sm.hdf -pp -i 148284 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/37213/37213_sm.hdf -pp -i 37213 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/63754/63754_sm.hdf -pp -i 63754 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/156846/156846_sm.hdf -pp -i 156846 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/179079/179079_sm.hdf -pp -i 179079 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/103459/103459_sm.hdf -pp -i 103459 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/K00274/K00274_sm.hdf -pp -i K00274 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/107181/107181_sm.hdf -pp -i 107181 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/31253/31253_sm.hdf -pp -i 31253 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/69960/69960_sm.hdf -pp -i 69960 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/168443/168443_sm.hdf -pp -i 168443 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/4203/4203_sm.hdf -pp -i 4203 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/K02720/K02720_sm.hdf -pp -i K02720 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/234314/234314_sm.hdf -pp -i 234314 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/211681/211681_sm.hdf -pp -i 211681 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/13871/13871_sm.hdf -pp -i 13871 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/31423/31423_sm.hdf -pp -i 31423 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/WASP14/WASP14_sm.hdf -pp -i WASP14 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/WASP17/WASP17_sm.hdf -pp -i WASP17 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/31560/31560_sm.hdf -pp -i 31560 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/18445/18445_sm.hdf -pp -i 18445 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/155712/155712_sm.hdf -pp -i 155712 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/24238/24238_sm.hdf -pp -i 24238 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/KIC8435766/KIC8435766_sm.hdf -pp -i KIC8435766 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/8553/8553_sm.hdf -pp -i 8553 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/80367/80367_sm.hdf -pp -i 80367 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/18143/18143_sm.hdf -pp -i 18143 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/137778/137778_sm.hdf -pp -i 137778 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/100623/100623_sm.hdf -pp -i 100623 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/116442/116442_sm.hdf -pp -i 116442 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/110743/110743_sm.hdf -pp -i 110743 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/155456/155456_sm.hdf -pp -i 155456 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/37394/37394_sm.hdf -pp -i 37394 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/131511/131511_sm.hdf -pp -i 131511 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/102195/102195_sm.hdf -pp -i 102195 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/72760/72760_sm.hdf -pp -i 72760 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/181234/181234_sm.hdf -pp -i 181234 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/37605/37605_sm.hdf -pp -i 37605 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/164922/164922_sm.hdf -pp -i 164922 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/K00137/K00137_sm.hdf -pp -i K00137 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/3795/3795_sm.hdf -pp -i 3795 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/K00245/K00245_sm.hdf -pp -i K00245 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/201924/201924_sm.hdf -pp -i 201924 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/221822/221822_sm.hdf -pp -i 221822 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/224619/224619_sm.hdf -pp -i 224619 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/126583/126583_sm.hdf -pp -i 126583 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/162232/162232_sm.hdf -pp -i 162232 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/133125/133125_sm.hdf -pp -i 133125 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/80606/80606_sm.hdf -pp -i 80606 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/193690/193690_sm.hdf -pp -i 193690 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/27496/27496_sm.hdf -pp -i 27496 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/112415/112415_sm.hdf -pp -i 112415 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/WASP8/WASP8_sm.hdf -pp -i WASP8 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/37124/37124_sm.hdf -pp -i 37124 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/43162/43162_sm.hdf -pp -i 43162 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/222038/222038_sm.hdf -pp -i 222038 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/172051/172051_sm.hdf -pp -i 172051 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/161479/161479_sm.hdf -pp -i 161479 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/209393/209393_sm.hdf -pp -i 209393 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/66428/66428_sm.hdf -pp -i 66428 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/135101A/135101A_sm.hdf -pp -i 135101A -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/21774/21774_sm.hdf -pp -i 21774 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/30708/30708_sm.hdf -pp -i 30708 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/110537/110537_sm.hdf -pp -i 110537 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/42807/42807_sm.hdf -pp -i 42807 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/K00261/K00261_sm.hdf -pp -i K00261 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/28005/28005_sm.hdf -pp -i 28005 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/38467/38467_sm.hdf -pp -i 38467 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/104437/104437_sm.hdf -pp -i 104437 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/175425/175425_sm.hdf -pp -i 175425 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/203473/203473_sm.hdf -pp -i 203473 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/56274/56274_sm.hdf -pp -i 56274 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/72687/72687_sm.hdf -pp -i 72687 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/149750/149750_sm.hdf -pp -i 149750 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/195034/195034_sm.hdf -pp -i 195034 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/109749/109749_sm.hdf -pp -i 109749 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/K00292/K00292_sm.hdf -pp -i K00292 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/13931/13931_sm.hdf -pp -i 13931 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/222986/222986_sm.hdf -pp -i 222986 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/68988/68988_sm.hdf -pp -i 68988 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/84737/84737_sm.hdf -pp -i 84737 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/101904/101904_sm.hdf -pp -i 101904 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/K00116/K00116_sm.hdf -pp -i K00116 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/124257A/124257A_sm.hdf -pp -i 124257A -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/1388/1388_sm.hdf -pp -i 1388 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/86081/86081_sm.hdf -pp -i 86081 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/150706/150706_sm.hdf -pp -i 150706 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/33636/33636_sm.hdf -pp -i 33636 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/17156/17156_sm.hdf -pp -i 17156 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/44985/44985_sm.hdf -pp -i 44985 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/122973/122973_sm.hdf -pp -i 122973 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/27859/27859_sm.hdf -pp -i 27859 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/26161/26161_sm.hdf -pp -i 26161 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/20367/20367_sm.hdf -pp -i 20367 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/103890/103890_sm.hdf -pp -i 103890 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/132254/132254_sm.hdf -pp -i 132254 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp lincomb /home/syee/specmatchemp-working/specmatchemp/results/3861/3861_sm.hdf -pp -i 3861 -o /home/syee/specmatchemp-working/specmatchemp/results
