source ~/.bash_profile; smemp match j06.1125 -pp -i 100623 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j20.1313 -pp -i 101904 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j15.2019 -pp -i 102195 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j72.386 -pp -i 102444 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j72.98 -pp -i 102956 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j117.364 -pp -i 103459 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j05.1265 -pp -i 103890 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j32.1740 -pp -i 104437 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j21.1217 -pp -i 106088 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j20.823 -pp -i 107181 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j72.389 -pp -i 108189 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j72.738 -pp -i 108863 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j72.387 -pp -i 109159 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j93.1277 -pp -i 109749 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j161.539 -pp -i 10995 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j189.2174 -pp -i 110463 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j06.1121 -pp -i 110537 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j19.940 -pp -i 110743 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j189.2172 -pp -i 110833 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j117.361 -pp -i 111814 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j21.1218 -pp -i 112415 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j189.2175 -pp -i 112914 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j72.741 -pp -i 114659 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j06.1134 -pp -i 116442 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j72.762 -pp -i 122253 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j20.824 -pp -i 122973 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j72.718 -pp -i 123239 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j06.1828 -pp -i 124257A -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j76.1671 -pp -i 125607 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j06.1818 -pp -i 126583 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j72.442 -pp -i 128311 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j130.1674 -pp -i 130048 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j189.1878 -pp -i 130307 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j189.270 -pp -i 131511 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j189.2471 -pp -i 131582 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j187.201 -pp -i 132254 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j19.942 -pp -i 133125 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j72.454 -pp -i 135101A -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j130.1675 -pp -i 135872 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j189.272 -pp -i 137778 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j140.96 -pp -i 13871 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j177.343 -pp -i 1388 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j64.152 -pp -i 13931 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j189.2183 -pp -i 144872 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j63.728 -pp -i 14655 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j62.180 -pp -i 14787 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j42.152 -pp -i 148284 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j130.1125 -pp -i 14855 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j32.1750 -pp -i 149750 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j59.1647 -pp -i 1502 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j150.733 -pp -i 150706 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j72.456 -pp -i 152581 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j72.146 -pp -i 152733 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j62.177 -pp -i 15336 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j189.2184 -pp -i 153525 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j23.520 -pp -i 155413 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j21.1529 -pp -i 155456 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j21.1249 -pp -i 155712 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j72.165 -pp -i 156846 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j21.1530 -pp -i 161479 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j55.930 -pp -i 162232 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j08.769 -pp -i 164922 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j72.169 -pp -i 168443 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j123.315 -pp -i 170657 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j21.1379 -pp -i 17156 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j59.987 -pp -i 172051 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j32.1388 -pp -i 175425 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j62.190 -pp -i 17620 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j32.1784 -pp -i 179079 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j193.70 -pp -i 181234 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j50.242 -pp -i 18143 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j187.82 -pp -i 18445 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j62.193 -pp -i 18742 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j13.2079 -pp -i 189733 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j63.381 -pp -i 190228 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j159.703 -pp -i 190571 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j55.977 -pp -i 193690 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j152.510 -pp -i 195034 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j55.1871 -pp -i 196124 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j138.778 -pp -i 199255 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j138.779 -pp -i 199381 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j57.145 -pp -i 200964 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j21.1578 -pp -i 201924 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j193.303 -pp -i 202575 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j55.962 -pp -i 203471 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j181.75 -pp -i 203473 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j185.1097 -pp -i 20367 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j62.88 -pp -i 206635 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j57.147 -pp -i 207077 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j63.384 -pp -i 208313 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j152.513 -pp -i 209393 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j156.1777 -pp -i 210373 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j179.529 -pp -i 211681 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j62.97 -pp -i 215049 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j62.98 -pp -i 216834 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j62.101 -pp -i 217681 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j187.92 -pp -i 21774 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j61.702 -pp -i 220339 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j62.106 -pp -i 221504 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j15.519 -pp -i 221822 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j21.1562 -pp -i 222038 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j23.1110 -pp -i 222986 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j41.2656 -pp -i 224619 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j62.200 -pp -i 22657 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j32.1749 -pp -i 234314 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j62.182 -pp -i 23825 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j76.1672 -pp -i 238433 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j50.268 -pp -i 24238 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j16.526 -pp -i 24892 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j62.205 -pp -i 26007 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j165.405 -pp -i 26161 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j62.206 -pp -i 26634 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j23.1578 -pp -i 27496 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j50.275 -pp -i 27859 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j50.266 -pp -i 28005 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j187.378 -pp -i 30708 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j63.441 -pp -i 31253 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j140.114 -pp -i 31423 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j81.639 -pp -i 31451 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j61.764 -pp -i 31560 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j85.329 -pp -i 33636 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j63.712 -pp -i 3404 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j62.152 -pp -i 3458 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j187.404 -pp -i 35112 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j194.134 -pp -i 3684 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j63.1056 -pp -i 37008 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j63.448 -pp -i 37124 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j187.113 -pp -i 37213 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j15.1500 -pp -i 37394 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j23.1581 -pp -i 37605 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j76.1925 -pp -i 3795 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j04.886 -pp -i 38467 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j34.254 -pp -i 3861 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j23.1583 -pp -i 39094 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j65.145 -pp -i 40537 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j78.495 -pp -i 4203 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j187.126 -pp -i 42807 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j59.1648 -pp -i 4313 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j15.563 -pp -i 43162 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j62.156 -pp -i 4395 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j187.118 -pp -i 44985 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j187.116 -pp -i 45067 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j133.647 -pp -i 48345 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j158.105 -pp -i 5133 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j187.388 -pp -i 53927 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j187.165 -pp -i 56274 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j23.1586 -pp -i 57204 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j62.139 -pp -i 6030 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j85.340 -pp -i 61606 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j118.389 -pp -i 61995 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j187.164 -pp -i 63754 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j65.146 -pp -i 64413 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j06.1076 -pp -i 66428 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j63.1658 -pp -i 68988 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j04.883 -pp -i 69960 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j70.389 -pp -i 72440 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j65.150 -pp -i 72490 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j83.360 -pp -i 72687 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j187.413 -pp -i 72760 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j70.390 -pp -i 74390 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j70.391 -pp -i 77818 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j187.162 -pp -i 80367 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j50.315 -pp -i 80606 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j62.163 -pp -i 8407 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j67.1020 -pp -i 84737 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j15.941 -pp -i 8553 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j130.2537 -pp -i 8594 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j15.1503 -pp -i 86081 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j166.94 -pp -i 87424 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j72.77 -pp -i 87883 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j55.1376 -pp -i 88133 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j90.988 -pp -i 88654 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j51.145 -pp -i 93396 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j18.685 -pp -i 95088 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j72.93 -pp -i 95526 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j62.165 -pp -i 9625 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j189.1673 -pp -i 96612 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j148.163 -pp -i CK01925 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j97.3187 -pp -i K00975 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j120.338 -pp -i K01612 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j192.299 -pp -i KIC10018963 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j193.688 -pp -i KIC10068307 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j193.734 -pp -i KIC10162436 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j128.152 -pp -i KIC10355856 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j193.701 -pp -i KIC10454113 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j128.153 -pp -i KIC10516096 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j128.154 -pp -i KIC10644253 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j193.703 -pp -i KIC10709834 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j128.157 -pp -i KIC11026764 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j193.704 -pp -i KIC11137075 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j193.700 -pp -i KIC11244118 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j193.732 -pp -i KIC11414712 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j128.498 -pp -i KIC11717120 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j128.500 -pp -i KIC12009504 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j128.502 -pp -i KIC12258514 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j193.712 -pp -i KIC1435467 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j128.104 -pp -i KIC3427720 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j128.105 -pp -i KIC3656476 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j128.107 -pp -i KIC4914923 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j128.108 -pp -i KIC5021689 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j193.708 -pp -i KIC5184732 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j193.706 -pp -i KIC5596656 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j128.116 -pp -i KIC5773345 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j128.117 -pp -i KIC5955122 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j192.501 -pp -i KIC6106415 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j193.709 -pp -i KIC6116048 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j190.416 -pp -i KIC6225718 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j193.717 -pp -i KIC6442183 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j128.125 -pp -i KIC6603624 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j193.727 -pp -i KIC6933899 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j190.415 -pp -i KIC7206837 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j193.718 -pp -i KIC7680114 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j128.130 -pp -i KIC7747078 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j193.719 -pp -i KIC7799349 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j128.133 -pp -i KIC7871531 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j152.86 -pp -i KIC7940546 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j193.721 -pp -i KIC7970740 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j128.132 -pp -i KIC7976303 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j193.722 -pp -i KIC8006161 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j192.298 -pp -i KIC8179536 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j128.140 -pp -i KIC8228742 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j193.736 -pp -i KIC8394589 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j193.735 -pp -i KIC8524425 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j193.692 -pp -i KIC8561221 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j193.693 -pp -i KIC8694723 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j128.141 -pp -i KIC8702606 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j193.694 -pp -i KIC8751420 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j193.695 -pp -i KIC8938364 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j193.737 -pp -i KIC9098294 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j128.143 -pp -i KIC9139151 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j192.499 -pp -i KIC9139163 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j128.144 -pp -i KIC9206432 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j137.108 -pp -i HIP10337 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j59.403 -pp -i HIP105341 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j59.1640 -pp -i HIP114156 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j59.1642 -pp -i HIP118261 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j59.1982 -pp -i HIP12493 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j137.116 -pp -i HIP15095 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j131.363 -pp -i HIP1532 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j14.622 -pp -i HIP19165 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j61.791 -pp -i HIP25220 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j61.466 -pp -i HIP36551 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j149.140 -pp -i HIP40375 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j149.142 -pp -i HIP40910 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j63.1698 -pp -i HIP45839 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j63.779 -pp -i HIP47201 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j63.1699 -pp -i HIP48411 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j134.232 -pp -i HIP4845 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j63.1701 -pp -i HIP54810 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j128.549 -pp -i HIP5663 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j90.713 -pp -i HIP66222 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j59.396 -pp -i HIP93871 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j59.397 -pp -i HIP97051 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j55.1182 -pp -i 111631 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j124.340 -pp -i 1326B -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j76.1490 -pp -i 157881 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j55.1440 -pp -i 165222 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j59.992 -pp -i 180617 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j134.384 -pp -i 209290 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j63.1050 -pp -i 232979 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j222.308 -pp -i 245409 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j149.110 -pp -i 265866 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j131.943 -pp -i 28343 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j209.268 -pp -i GJ628 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j15.1926 -pp -i GL105B -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j78.491 -pp -i GL109 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j50.296 -pp -i GL2066 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j63.473 -pp -i GL239 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j15.1505 -pp -i GL250B -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j82.219 -pp -i GL273 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j118.811 -pp -i GL382 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j55.1377 -pp -i GL393 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j55.901 -pp -i GL514 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j35.852 -pp -i GL625 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j59.1273 -pp -i GL686 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j59.1283 -pp -i GL694 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j97.2588 -pp -i GL745A -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j59.1030 -pp -i GL806 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j222.304 -pp -i GL83.1 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j61.724 -pp -i GL87 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j190.1206 -pp -i GL875 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j193.921 -pp -i GL896A -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j38.271 -pp -i GL908 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j59.2216 -pp -i HIP104432 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j02.945 -pp -i HIP109388 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j64.154 -pp -i HIP11048 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j222.273 -pp -i HIP115332 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j15.943 -pp -i HIP115562 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j165.57 -pp -i HIP15366 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j15.517 -pp -i HIP1734 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j85.326 -pp -i HIP21556 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j97.2842 -pp -i HIP22762 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j222.99 -pp -i HIP23512 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j06.1476 -pp -i HIP36338 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j15.1501 -pp -i HIP36834 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j15.564 -pp -i HIP37217 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j06.1489 -pp -i HIP46769 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j149.148 -pp -i HIP47513 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j118.812 -pp -i HIP51007 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j222.76 -pp -i HIP5643 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j82.247 -pp -i HIP57050 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j06.1485 -pp -i HIP57548 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j67.506 -pp -i HIP59748 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j67.535 -pp -i HIP60093 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j92.111 -pp -i HIP61706 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j67.533 -pp -i HIP65016 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j222.752 -pp -i HIP71253 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j82.722 -pp -i HIP8051 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j153.114 -pp -i HIP91699 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j189.1669 -pp -i 101501 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j13.2064 -pp -i 10476 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j78.493 -pp -i 10697 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j01.1093 -pp -i 10700 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j185.1189 -pp -i 107383 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j180.740 -pp -i 10780 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j06.1131 -pp -i 115617 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j72.745 -pp -i 117176 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j01.1088 -pp -i 11964A -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j55.902 -pp -i 119850 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j222.343 -pp -i 120136 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j187.198 -pp -i 126660 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j187.196 -pp -i 130948 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j187.193 -pp -i 131156 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j08.880 -pp -i 1326 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j179.71 -pp -i 136202 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j70.465 -pp -i 143761 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j55.1237 -pp -i 145675 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j01.182 -pp -i 1461 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j222.759 -pp -i 149661 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j59.1282 -pp -i 157214 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j61.668 -pp -i 158633 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j23.1115 -pp -i 16160 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j59.1280 -pp -i 161797 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j187.472 -pp -i 164259 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j21.1376 -pp -i 166 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j179.143 -pp -i 16765 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j187.489 -pp -i 168151 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j185.804 -pp -i 16895 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j187.478 -pp -i 173667 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j187.482 -pp -i 173701 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j55.1240 -pp -i 173739 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j55.1241 -pp -i 173740 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j173.399 -pp -i 177153 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j188.905 -pp -i 181420 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j08.774 -pp -i 182572 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j174.501 -pp -i 182736 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j01.169 -pp -i 185144 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j55.1848 -pp -i 186408 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j55.1849 -pp -i 186427 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j188.560 -pp -i 187637 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j23.524 -pp -i 188512 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j01.1090 -pp -i 190360 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j59.1923 -pp -i 190406 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j76.1541 -pp -i 19373 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j72.176 -pp -i 195564 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j59.1033 -pp -i 199305 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j185.1131 -pp -i 19994 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j08.1233 -pp -i 201091 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j08.1230 -pp -i 201092 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j173.1211 -pp -i 206860 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j185.1120 -pp -i 21019 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j156.1776 -pp -i 210702 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j59.1926 -pp -i 216899 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j23.1103 -pp -i 217014 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j55.1281 -pp -i 217107 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j59.2221 -pp -i 217987 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j08.870 -pp -i 219134 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j130.1517 -pp -i 219623 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j26.532 -pp -i 222368 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j137.243 -pp -i 22484 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j63.431 -pp -i 23249 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j06.1045 -pp -i 26965 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j185.783 -pp -i 30652 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j06.1066 -pp -i 34411 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j85.328 -pp -i 36395 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j13.2073 -pp -i 3651 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j06.1054 -pp -i 38858 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j185.1109 -pp -i 39587 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j61.705 -pp -i 4628 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j185.1112 -pp -i 48737 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j185.1115 -pp -i 49933 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j185.652 -pp -i 58946 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j173.1218 -pp -i 6210 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j185.1106 -pp -i 69897 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j06.1091 -pp -i 75732 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j63.1374 -pp -i 79210 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j13.2095 -pp -i 7924 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j187.392 -pp -i 82885 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j06.1085 -pp -i 86728 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j72.72 -pp -i 88230 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j06.1099 -pp -i 95735 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j216.111 -pp -i GJ176 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j185.1133 -pp -i GL144 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j185.874 -pp -i GL338B -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j50.359 -pp -i GL412A -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j55.906 -pp -i GL570B -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j172.1087 -pp -i GL687 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j20.452 -pp -i GL699 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j187.474 -pp -i GL702A -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j187.477 -pp -i GL702B -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j45.596 -pp -i GL876 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j06.1488 -pp -i HIP57087 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j23.519 -pp -i HIP74995 -o /home/syee/specmatchemp-working/specmatchemp/results
source ~/.bash_profile; smemp match j59.1277 -pp -i HIP83043 -o /home/syee/specmatchemp-working/specmatchemp/results
