source ~/.bash_profile; smemp shift j06.1125 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 100623
source ~/.bash_profile; smemp shift j20.1313 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 101904
source ~/.bash_profile; smemp shift j15.2019 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 102195
source ~/.bash_profile; smemp shift j72.386 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 102444
source ~/.bash_profile; smemp shift j72.98 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 102956
source ~/.bash_profile; smemp shift j117.364 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 103459
source ~/.bash_profile; smemp shift j05.1265 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 103890
source ~/.bash_profile; smemp shift j32.1740 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 104437
source ~/.bash_profile; smemp shift j21.1217 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 106088
source ~/.bash_profile; smemp shift j20.823 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 107181
source ~/.bash_profile; smemp shift j72.389 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 108189
source ~/.bash_profile; smemp shift j72.738 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 108863
source ~/.bash_profile; smemp shift j72.387 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 109159
source ~/.bash_profile; smemp shift j93.1277 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 109749
source ~/.bash_profile; smemp shift j161.539 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 10995
source ~/.bash_profile; smemp shift j189.2174 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 110463
source ~/.bash_profile; smemp shift j06.1121 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 110537
source ~/.bash_profile; smemp shift j19.940 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 110743
source ~/.bash_profile; smemp shift j189.2172 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 110833
source ~/.bash_profile; smemp shift j117.361 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 111814
source ~/.bash_profile; smemp shift j21.1218 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 112415
source ~/.bash_profile; smemp shift j189.2175 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 112914
source ~/.bash_profile; smemp shift j72.741 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 114659
source ~/.bash_profile; smemp shift j06.1134 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 116442
source ~/.bash_profile; smemp shift j72.762 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 122253
source ~/.bash_profile; smemp shift j20.824 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 122973
source ~/.bash_profile; smemp shift j72.718 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 123239
source ~/.bash_profile; smemp shift j06.1828 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 124257A
source ~/.bash_profile; smemp shift j76.1671 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 125607
source ~/.bash_profile; smemp shift j06.1818 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 126583
source ~/.bash_profile; smemp shift j72.442 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 128311
source ~/.bash_profile; smemp shift j130.1674 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 130048
source ~/.bash_profile; smemp shift j189.1878 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 130307
source ~/.bash_profile; smemp shift j189.270 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 131511
source ~/.bash_profile; smemp shift j189.2471 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 131582
source ~/.bash_profile; smemp shift j187.201 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 132254
source ~/.bash_profile; smemp shift j19.942 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 133125
source ~/.bash_profile; smemp shift j72.454 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 135101A
source ~/.bash_profile; smemp shift j130.1675 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 135872
source ~/.bash_profile; smemp shift j189.272 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 137778
source ~/.bash_profile; smemp shift j140.96 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 13871
source ~/.bash_profile; smemp shift j177.343 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 1388
source ~/.bash_profile; smemp shift j64.152 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 13931
source ~/.bash_profile; smemp shift j189.2183 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 144872
source ~/.bash_profile; smemp shift j63.728 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 14655
source ~/.bash_profile; smemp shift j62.180 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 14787
source ~/.bash_profile; smemp shift j42.152 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 148284
source ~/.bash_profile; smemp shift j130.1125 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 14855
source ~/.bash_profile; smemp shift j32.1750 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 149750
source ~/.bash_profile; smemp shift j59.1647 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 1502
source ~/.bash_profile; smemp shift j150.733 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 150706
source ~/.bash_profile; smemp shift j72.456 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 152581
source ~/.bash_profile; smemp shift j72.146 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 152733
source ~/.bash_profile; smemp shift j62.177 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 15336
source ~/.bash_profile; smemp shift j189.2184 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 153525
source ~/.bash_profile; smemp shift j23.520 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 155413
source ~/.bash_profile; smemp shift j21.1529 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 155456
source ~/.bash_profile; smemp shift j21.1249 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 155712
source ~/.bash_profile; smemp shift j72.165 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 156846
source ~/.bash_profile; smemp shift j21.1530 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 161479
source ~/.bash_profile; smemp shift j55.930 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 162232
source ~/.bash_profile; smemp shift j08.769 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 164922
source ~/.bash_profile; smemp shift j72.169 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 168443
source ~/.bash_profile; smemp shift j123.315 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 170657
source ~/.bash_profile; smemp shift j21.1379 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 17156
source ~/.bash_profile; smemp shift j59.987 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 172051
source ~/.bash_profile; smemp shift j32.1388 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 175425
source ~/.bash_profile; smemp shift j62.190 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 17620
source ~/.bash_profile; smemp shift j32.1784 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 179079
source ~/.bash_profile; smemp shift j193.70 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 181234
source ~/.bash_profile; smemp shift j50.242 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 18143
source ~/.bash_profile; smemp shift j187.82 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 18445
source ~/.bash_profile; smemp shift j62.193 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 18742
source ~/.bash_profile; smemp shift j13.2079 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 189733
source ~/.bash_profile; smemp shift j63.381 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 190228
source ~/.bash_profile; smemp shift j159.703 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 190571
source ~/.bash_profile; smemp shift j55.977 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 193690
source ~/.bash_profile; smemp shift j152.510 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 195034
source ~/.bash_profile; smemp shift j55.1871 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 196124
source ~/.bash_profile; smemp shift j138.778 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 199255
source ~/.bash_profile; smemp shift j138.779 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 199381
source ~/.bash_profile; smemp shift j57.145 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 200964
source ~/.bash_profile; smemp shift j21.1578 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 201924
source ~/.bash_profile; smemp shift j193.303 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 202575
source ~/.bash_profile; smemp shift j55.962 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 203471
source ~/.bash_profile; smemp shift j181.75 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 203473
source ~/.bash_profile; smemp shift j185.1097 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 20367
source ~/.bash_profile; smemp shift j62.88 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 206635
source ~/.bash_profile; smemp shift j57.147 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 207077
source ~/.bash_profile; smemp shift j63.384 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 208313
source ~/.bash_profile; smemp shift j152.513 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 209393
source ~/.bash_profile; smemp shift j156.1777 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 210373
source ~/.bash_profile; smemp shift j179.529 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 211681
source ~/.bash_profile; smemp shift j62.97 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 215049
source ~/.bash_profile; smemp shift j62.98 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 216834
source ~/.bash_profile; smemp shift j62.101 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 217681
source ~/.bash_profile; smemp shift j187.92 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 21774
source ~/.bash_profile; smemp shift j61.702 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 220339
source ~/.bash_profile; smemp shift j62.106 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 221504
source ~/.bash_profile; smemp shift j15.519 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 221822
source ~/.bash_profile; smemp shift j21.1562 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 222038
source ~/.bash_profile; smemp shift j23.1110 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 222986
source ~/.bash_profile; smemp shift j41.2656 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 224619
source ~/.bash_profile; smemp shift j62.200 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 22657
source ~/.bash_profile; smemp shift j32.1749 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 234314
source ~/.bash_profile; smemp shift j62.182 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 23825
source ~/.bash_profile; smemp shift j76.1672 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 238433
source ~/.bash_profile; smemp shift j50.268 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 24238
source ~/.bash_profile; smemp shift j16.526 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 24892
source ~/.bash_profile; smemp shift j62.205 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 26007
source ~/.bash_profile; smemp shift j165.405 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 26161
source ~/.bash_profile; smemp shift j62.206 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 26634
source ~/.bash_profile; smemp shift j23.1578 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 27496
source ~/.bash_profile; smemp shift j50.275 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 27859
source ~/.bash_profile; smemp shift j50.266 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 28005
source ~/.bash_profile; smemp shift j187.378 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 30708
source ~/.bash_profile; smemp shift j63.441 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 31253
source ~/.bash_profile; smemp shift j140.114 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 31423
source ~/.bash_profile; smemp shift j81.639 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 31451
source ~/.bash_profile; smemp shift j61.764 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 31560
source ~/.bash_profile; smemp shift j85.329 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 33636
source ~/.bash_profile; smemp shift j63.712 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 3404
source ~/.bash_profile; smemp shift j62.152 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 3458
source ~/.bash_profile; smemp shift j187.404 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 35112
source ~/.bash_profile; smemp shift j194.134 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 3684
source ~/.bash_profile; smemp shift j63.1056 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 37008
source ~/.bash_profile; smemp shift j63.448 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 37124
source ~/.bash_profile; smemp shift j187.113 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 37213
source ~/.bash_profile; smemp shift j15.1500 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 37394
source ~/.bash_profile; smemp shift j23.1581 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 37605
source ~/.bash_profile; smemp shift j76.1925 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 3795
source ~/.bash_profile; smemp shift j04.886 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 38467
source ~/.bash_profile; smemp shift j34.254 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 3861
source ~/.bash_profile; smemp shift j23.1583 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 39094
source ~/.bash_profile; smemp shift j65.145 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 40537
source ~/.bash_profile; smemp shift j78.495 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 4203
source ~/.bash_profile; smemp shift j187.126 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 42807
source ~/.bash_profile; smemp shift j59.1648 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 4313
source ~/.bash_profile; smemp shift j15.563 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 43162
source ~/.bash_profile; smemp shift j62.156 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 4395
source ~/.bash_profile; smemp shift j187.118 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 44985
source ~/.bash_profile; smemp shift j187.116 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 45067
source ~/.bash_profile; smemp shift j133.647 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 48345
source ~/.bash_profile; smemp shift j158.105 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 5133
source ~/.bash_profile; smemp shift j187.388 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 53927
source ~/.bash_profile; smemp shift j187.165 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 56274
source ~/.bash_profile; smemp shift j23.1586 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 57204
source ~/.bash_profile; smemp shift j62.139 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 6030
source ~/.bash_profile; smemp shift j85.340 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 61606
source ~/.bash_profile; smemp shift j118.389 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 61995
source ~/.bash_profile; smemp shift j187.164 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 63754
source ~/.bash_profile; smemp shift j65.146 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 64413
source ~/.bash_profile; smemp shift j06.1076 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 66428
source ~/.bash_profile; smemp shift j63.1658 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 68988
source ~/.bash_profile; smemp shift j04.883 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 69960
source ~/.bash_profile; smemp shift j70.389 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 72440
source ~/.bash_profile; smemp shift j65.150 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 72490
source ~/.bash_profile; smemp shift j83.360 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 72687
source ~/.bash_profile; smemp shift j187.413 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 72760
source ~/.bash_profile; smemp shift j70.390 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 74390
source ~/.bash_profile; smemp shift j70.391 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 77818
source ~/.bash_profile; smemp shift j187.162 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 80367
source ~/.bash_profile; smemp shift j50.315 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 80606
source ~/.bash_profile; smemp shift j62.163 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 8407
source ~/.bash_profile; smemp shift j67.1020 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 84737
source ~/.bash_profile; smemp shift j15.941 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 8553
source ~/.bash_profile; smemp shift j130.2537 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 8594
source ~/.bash_profile; smemp shift j15.1503 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 86081
source ~/.bash_profile; smemp shift j166.94 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 87424
source ~/.bash_profile; smemp shift j72.77 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 87883
source ~/.bash_profile; smemp shift j55.1376 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 88133
source ~/.bash_profile; smemp shift j90.988 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 88654
source ~/.bash_profile; smemp shift j51.145 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 93396
source ~/.bash_profile; smemp shift j18.685 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 95088
source ~/.bash_profile; smemp shift j72.93 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 95526
source ~/.bash_profile; smemp shift j62.165 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 9625
source ~/.bash_profile; smemp shift j189.1673 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 96612
source ~/.bash_profile; smemp shift j148.163 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n CK01925
source ~/.bash_profile; smemp shift j97.3187 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n K00975
source ~/.bash_profile; smemp shift j120.338 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n K01612
source ~/.bash_profile; smemp shift j192.299 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC10018963
source ~/.bash_profile; smemp shift j193.688 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC10068307
source ~/.bash_profile; smemp shift j193.734 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC10162436
source ~/.bash_profile; smemp shift j128.152 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC10355856
source ~/.bash_profile; smemp shift j193.701 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC10454113
source ~/.bash_profile; smemp shift j128.153 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC10516096
source ~/.bash_profile; smemp shift j128.154 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC10644253
source ~/.bash_profile; smemp shift j193.703 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC10709834
source ~/.bash_profile; smemp shift j128.157 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC11026764
source ~/.bash_profile; smemp shift j193.704 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC11137075
source ~/.bash_profile; smemp shift j193.700 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC11244118
source ~/.bash_profile; smemp shift j193.732 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC11414712
source ~/.bash_profile; smemp shift j128.498 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC11717120
source ~/.bash_profile; smemp shift j128.500 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC12009504
source ~/.bash_profile; smemp shift j128.502 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC12258514
source ~/.bash_profile; smemp shift j193.712 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC1435467
source ~/.bash_profile; smemp shift j128.104 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC3427720
source ~/.bash_profile; smemp shift j128.105 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC3656476
source ~/.bash_profile; smemp shift j128.107 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC4914923
source ~/.bash_profile; smemp shift j128.108 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC5021689
source ~/.bash_profile; smemp shift j193.708 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC5184732
source ~/.bash_profile; smemp shift j193.706 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC5596656
source ~/.bash_profile; smemp shift j128.116 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC5773345
source ~/.bash_profile; smemp shift j128.117 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC5955122
source ~/.bash_profile; smemp shift j192.501 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC6106415
source ~/.bash_profile; smemp shift j193.709 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC6116048
source ~/.bash_profile; smemp shift j190.416 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC6225718
source ~/.bash_profile; smemp shift j193.717 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC6442183
source ~/.bash_profile; smemp shift j128.125 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC6603624
source ~/.bash_profile; smemp shift j193.727 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC6933899
source ~/.bash_profile; smemp shift j190.415 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC7206837
source ~/.bash_profile; smemp shift j193.718 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC7680114
source ~/.bash_profile; smemp shift j128.130 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC7747078
source ~/.bash_profile; smemp shift j193.719 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC7799349
source ~/.bash_profile; smemp shift j128.133 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC7871531
source ~/.bash_profile; smemp shift j152.86 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC7940546
source ~/.bash_profile; smemp shift j193.721 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC7970740
source ~/.bash_profile; smemp shift j128.132 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC7976303
source ~/.bash_profile; smemp shift j193.722 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC8006161
source ~/.bash_profile; smemp shift j192.298 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC8179536
source ~/.bash_profile; smemp shift j128.140 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC8228742
source ~/.bash_profile; smemp shift j193.736 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC8394589
source ~/.bash_profile; smemp shift j193.735 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC8524425
source ~/.bash_profile; smemp shift j193.692 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC8561221
source ~/.bash_profile; smemp shift j193.693 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC8694723
source ~/.bash_profile; smemp shift j128.141 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC8702606
source ~/.bash_profile; smemp shift j193.694 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC8751420
source ~/.bash_profile; smemp shift j193.695 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC8938364
source ~/.bash_profile; smemp shift j193.737 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC9098294
source ~/.bash_profile; smemp shift j128.143 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC9139151
source ~/.bash_profile; smemp shift j192.499 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC9139163
source ~/.bash_profile; smemp shift j128.144 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n KIC9206432
source ~/.bash_profile; smemp shift j137.108 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP10337
source ~/.bash_profile; smemp shift j59.403 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP105341
source ~/.bash_profile; smemp shift j59.1640 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP114156
source ~/.bash_profile; smemp shift j59.1642 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP118261
source ~/.bash_profile; smemp shift j59.1982 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP12493
source ~/.bash_profile; smemp shift j137.116 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP15095
source ~/.bash_profile; smemp shift j131.363 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP1532
source ~/.bash_profile; smemp shift j14.622 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP19165
source ~/.bash_profile; smemp shift j61.791 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP25220
source ~/.bash_profile; smemp shift j61.466 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP36551
source ~/.bash_profile; smemp shift j149.140 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP40375
source ~/.bash_profile; smemp shift j149.142 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP40910
source ~/.bash_profile; smemp shift j63.1698 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP45839
source ~/.bash_profile; smemp shift j63.779 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP47201
source ~/.bash_profile; smemp shift j63.1699 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP48411
source ~/.bash_profile; smemp shift j134.232 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP4845
source ~/.bash_profile; smemp shift j63.1701 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP54810
source ~/.bash_profile; smemp shift j128.549 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP5663
source ~/.bash_profile; smemp shift j90.713 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP66222
source ~/.bash_profile; smemp shift j59.396 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP93871
source ~/.bash_profile; smemp shift j59.397 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP97051
source ~/.bash_profile; smemp shift j55.1182 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 111631
source ~/.bash_profile; smemp shift j124.340 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 1326B
source ~/.bash_profile; smemp shift j76.1490 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 157881
source ~/.bash_profile; smemp shift j55.1440 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 165222
source ~/.bash_profile; smemp shift j59.992 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 180617
source ~/.bash_profile; smemp shift j134.384 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 209290
source ~/.bash_profile; smemp shift j63.1050 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 232979
source ~/.bash_profile; smemp shift j222.308 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 245409
source ~/.bash_profile; smemp shift j149.110 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 265866
source ~/.bash_profile; smemp shift j131.943 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 28343
source ~/.bash_profile; smemp shift j209.268 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n GJ628
source ~/.bash_profile; smemp shift j15.1926 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n GL105B
source ~/.bash_profile; smemp shift j78.491 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n GL109
source ~/.bash_profile; smemp shift j50.296 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n GL2066
source ~/.bash_profile; smemp shift j63.473 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n GL239
source ~/.bash_profile; smemp shift j15.1505 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n GL250B
source ~/.bash_profile; smemp shift j82.219 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n GL273
source ~/.bash_profile; smemp shift j118.811 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n GL382
source ~/.bash_profile; smemp shift j55.1377 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n GL393
source ~/.bash_profile; smemp shift j55.901 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n GL514
source ~/.bash_profile; smemp shift j35.852 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n GL625
source ~/.bash_profile; smemp shift j59.1273 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n GL686
source ~/.bash_profile; smemp shift j59.1283 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n GL694
source ~/.bash_profile; smemp shift j97.2588 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n GL745A
source ~/.bash_profile; smemp shift j59.1030 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n GL806
source ~/.bash_profile; smemp shift j222.304 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n GL83.1
source ~/.bash_profile; smemp shift j61.724 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n GL87
source ~/.bash_profile; smemp shift j190.1206 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n GL875
source ~/.bash_profile; smemp shift j193.921 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n GL896A
source ~/.bash_profile; smemp shift j38.271 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n GL908
source ~/.bash_profile; smemp shift j59.2216 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP104432
source ~/.bash_profile; smemp shift j02.945 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP109388
source ~/.bash_profile; smemp shift j64.154 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP11048
source ~/.bash_profile; smemp shift j222.273 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP115332
source ~/.bash_profile; smemp shift j15.943 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP115562
source ~/.bash_profile; smemp shift j165.57 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP15366
source ~/.bash_profile; smemp shift j15.517 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP1734
source ~/.bash_profile; smemp shift j85.326 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP21556
source ~/.bash_profile; smemp shift j97.2842 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP22762
source ~/.bash_profile; smemp shift j222.99 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP23512
source ~/.bash_profile; smemp shift j06.1476 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP36338
source ~/.bash_profile; smemp shift j15.1501 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP36834
source ~/.bash_profile; smemp shift j15.564 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP37217
source ~/.bash_profile; smemp shift j06.1489 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP46769
source ~/.bash_profile; smemp shift j149.148 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP47513
source ~/.bash_profile; smemp shift j118.812 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP51007
source ~/.bash_profile; smemp shift j222.76 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP5643
source ~/.bash_profile; smemp shift j82.247 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP57050
source ~/.bash_profile; smemp shift j06.1485 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP57548
source ~/.bash_profile; smemp shift j67.506 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP59748
source ~/.bash_profile; smemp shift j67.535 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP60093
source ~/.bash_profile; smemp shift j92.111 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP61706
source ~/.bash_profile; smemp shift j67.533 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP65016
source ~/.bash_profile; smemp shift j222.752 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP71253
source ~/.bash_profile; smemp shift j82.722 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP8051
source ~/.bash_profile; smemp shift j153.114 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP91699
source ~/.bash_profile; smemp shift j189.1669 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 101501
source ~/.bash_profile; smemp shift j13.2064 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 10476
source ~/.bash_profile; smemp shift j78.493 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 10697
source ~/.bash_profile; smemp shift j01.1093 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 10700
source ~/.bash_profile; smemp shift j185.1189 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 107383
source ~/.bash_profile; smemp shift j180.740 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 10780
source ~/.bash_profile; smemp shift j06.1131 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 115617
source ~/.bash_profile; smemp shift j72.745 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 117176
source ~/.bash_profile; smemp shift j01.1088 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 11964A
source ~/.bash_profile; smemp shift j55.902 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 119850
source ~/.bash_profile; smemp shift j222.343 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 120136
source ~/.bash_profile; smemp shift j187.198 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 126660
source ~/.bash_profile; smemp shift j187.196 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 130948
source ~/.bash_profile; smemp shift j187.193 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 131156
source ~/.bash_profile; smemp shift j08.880 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 1326
source ~/.bash_profile; smemp shift j179.71 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 136202
source ~/.bash_profile; smemp shift j70.465 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 143761
source ~/.bash_profile; smemp shift j55.1237 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 145675
source ~/.bash_profile; smemp shift j01.182 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 1461
source ~/.bash_profile; smemp shift j222.759 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 149661
source ~/.bash_profile; smemp shift j59.1282 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 157214
source ~/.bash_profile; smemp shift j61.668 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 158633
source ~/.bash_profile; smemp shift j23.1115 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 16160
source ~/.bash_profile; smemp shift j59.1280 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 161797
source ~/.bash_profile; smemp shift j187.472 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 164259
source ~/.bash_profile; smemp shift j21.1376 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 166
source ~/.bash_profile; smemp shift j179.143 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 16765
source ~/.bash_profile; smemp shift j187.489 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 168151
source ~/.bash_profile; smemp shift j185.804 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 16895
source ~/.bash_profile; smemp shift j187.478 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 173667
source ~/.bash_profile; smemp shift j187.482 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 173701
source ~/.bash_profile; smemp shift j55.1240 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 173739
source ~/.bash_profile; smemp shift j55.1241 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 173740
source ~/.bash_profile; smemp shift j173.399 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 177153
source ~/.bash_profile; smemp shift j188.905 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 181420
source ~/.bash_profile; smemp shift j08.774 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 182572
source ~/.bash_profile; smemp shift j174.501 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 182736
source ~/.bash_profile; smemp shift j01.169 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 185144
source ~/.bash_profile; smemp shift j55.1848 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 186408
source ~/.bash_profile; smemp shift j55.1849 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 186427
source ~/.bash_profile; smemp shift j188.560 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 187637
source ~/.bash_profile; smemp shift j23.524 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 188512
source ~/.bash_profile; smemp shift j01.1090 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 190360
source ~/.bash_profile; smemp shift j59.1923 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 190406
source ~/.bash_profile; smemp shift j76.1541 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 19373
source ~/.bash_profile; smemp shift j72.176 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 195564
source ~/.bash_profile; smemp shift j59.1033 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 199305
source ~/.bash_profile; smemp shift j185.1131 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 19994
source ~/.bash_profile; smemp shift j08.1233 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 201091
source ~/.bash_profile; smemp shift j08.1230 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 201092
source ~/.bash_profile; smemp shift j173.1211 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 206860
source ~/.bash_profile; smemp shift j185.1120 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 21019
source ~/.bash_profile; smemp shift j156.1776 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 210702
source ~/.bash_profile; smemp shift j59.1926 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 216899
source ~/.bash_profile; smemp shift j23.1103 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 217014
source ~/.bash_profile; smemp shift j55.1281 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 217107
source ~/.bash_profile; smemp shift j59.2221 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 217987
source ~/.bash_profile; smemp shift j08.870 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 219134
source ~/.bash_profile; smemp shift j130.1517 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 219623
source ~/.bash_profile; smemp shift j26.532 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 222368
source ~/.bash_profile; smemp shift j137.243 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 22484
source ~/.bash_profile; smemp shift j63.431 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 23249
source ~/.bash_profile; smemp shift j06.1045 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 26965
source ~/.bash_profile; smemp shift j185.783 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 30652
source ~/.bash_profile; smemp shift j06.1066 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 34411
source ~/.bash_profile; smemp shift j85.328 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 36395
source ~/.bash_profile; smemp shift j13.2073 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 3651
source ~/.bash_profile; smemp shift j06.1054 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 38858
source ~/.bash_profile; smemp shift j185.1109 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 39587
source ~/.bash_profile; smemp shift j61.705 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 4628
source ~/.bash_profile; smemp shift j185.1112 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 48737
source ~/.bash_profile; smemp shift j185.1115 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 49933
source ~/.bash_profile; smemp shift j185.652 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 58946
source ~/.bash_profile; smemp shift j173.1218 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 6210
source ~/.bash_profile; smemp shift j185.1106 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 69897
source ~/.bash_profile; smemp shift j06.1091 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 75732
source ~/.bash_profile; smemp shift j63.1374 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 79210
source ~/.bash_profile; smemp shift j13.2095 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 7924
source ~/.bash_profile; smemp shift j187.392 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 82885
source ~/.bash_profile; smemp shift j06.1085 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 86728
source ~/.bash_profile; smemp shift j72.72 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 88230
source ~/.bash_profile; smemp shift j06.1099 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n 95735
source ~/.bash_profile; smemp shift j216.111 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n GJ176
source ~/.bash_profile; smemp shift j185.1133 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n GL144
source ~/.bash_profile; smemp shift j185.874 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n GL338B
source ~/.bash_profile; smemp shift j50.359 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n GL412A
source ~/.bash_profile; smemp shift j55.906 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n GL570B
source ~/.bash_profile; smemp shift j172.1087 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n GL687
source ~/.bash_profile; smemp shift j20.452 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n GL699
source ~/.bash_profile; smemp shift j187.474 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n GL702A
source ~/.bash_profile; smemp shift j187.477 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n GL702B
source ~/.bash_profile; smemp shift j45.596 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n GL876
source ~/.bash_profile; smemp shift j06.1488 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP57087
source ~/.bash_profile; smemp shift j23.519 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP74995
source ~/.bash_profile; smemp shift j59.1277 -pp -f -r /home/syee/specmatchemp-working/specmatchemp/results_all_orders/ -n HIP83043
